name: pizza_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1
  
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  cloud_functions: ^5.3.2
  cupertino_icons: ^1.0.8
  firebase_storage: ^12.4.2
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  font_awesome_flutter: ^10.8.0

  user_repository:
    path: D:/pizza_app/packages/user_repository
  pizza_repository:
    path: D:/Pizza-Application/packages/pizza_repository
  firebase_core_web: ^2.20.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
