name: pizza_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1
  
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  cloud_functions: ^5.3.2
  cupertino_icons: ^1.0.8
  firebase_storage: ^12.4.2
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  font_awesome_flutter: ^10.8.0
  firebase_core_web: ^2.20.0
  intl: ^0.20.2
  collection: ^1.19.1
  image_picker: ^1.1.2
  flutter_typeahead: ^5.2.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  image_picker_for_web: ^3.0.6
  dropdown_button2: ^2.3.9
  http: 0.13.6

#  google_maps_flutter: ^2.10.0
#  flutter_google_places_hoc081098: ^2.0.0-beta.0
#  google_api_headers: ^4.4.1


  user_repository:
    path: D:/Pizza-Application/packages/user_repository
  pizza_repository:
    path: D:/Pizza-Application/packages/pizza_repository
  flutter_dotenv: ^5.2.1
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  uuid: ^4.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env
