name: pizza_repository
description: "The Repo handles pizzas"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  # equatable: ^2.0.7
  # firebase_auth: ^5.4.1
  # firebase_storage: ^12.4.1
  # cupertino_icons: ^1.0.8
  # rxdart: ^0.28.0
  path: ^1.9.0
  cloud_firestore: ^5.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true